# pubspec.yaml

name: energy_monitor
description: An app to help households track and reduce electricity use.
publish_to: 'none' 

version: 1.0.0+1

environment:         # <--- THIS IS THE 'environment' BLOCK
  sdk: '^3.8.0'      # <--- THIS IS WHERE YOU MAKE THE CHANGE

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.0
  provider: ^6.0.5
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  # Date and Time Utilities
  intl: ^0.18.1
  # Charting
  fl_chart: ^0.68.0
  # Notifications
  flutter_local_notifications: ^17.1.0
  # File Export
  csv: ^6.0.0
  excel: ^4.0.6
  pdf: ^3.10.4
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6